{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a33ebd3c-c5c2-463d-8f46-bfbff63f10a5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import logging\n",
    "import re\n",
    "import os\n",
    "import yaml\n",
    "from pathlib import Path\n",
    "import requests\n",
    "\n",
    "# Настройка логирования\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n",
    "    handlers=[\n",
    "        logging.StreamHandler()  # Только вывод в консоль\n",
    "    ]\n",
    ")\n",
    "logger = logging.getLogger('FinamWebhook')\n",
    "\n",
    "# Загрузка конфига\n",
    "def load_config():\n",
    "    try:\n",
    "        config_path = Path(__file__).parent / 'config.yaml'\n",
    "        with open(config_path) as f:\n",
    "            return yaml.safe_load(f)\n",
    "    except Exception as e:\n",
    "        logger.critical(f\"Config load error: {str(e)}\")\n",
    "        raise\n",
    "\n",
    "CONFIG = load_config()\n",
    "\n",
    "class OrderManager:\n",
    "    def __init__(self):\n",
    "        self.slippage = CONFIG['risk_management']['slippage']\n",
    "        self.max_quantity = CONFIG['risk_management']['max_quantity']\n",
    "        self.allowed_actions = CONFIG['tradingview']['allowed_actions']\n",
    "        \n",
    "    def apply_slippage(self, price, action):\n",
    "        \"\"\"Применяет проскальзывание к цене с валидацией\"\"\"\n",
    "        try:\n",
    "            price = float(price)\n",
    "            if action.lower() == 'buy':\n",
    "                return round(price + self.slippage, 2)\n",
    "            elif action.lower() == 'sell':\n",
    "                return round(price - self.slippage, 2)\n",
    "            return price\n",
    "        except Exception as e:\n",
    "            logger.error(f\"Slippage error: {str(e)}\")\n",
    "            return price\n",
    "\n",
    "    def validate_ticker(self, ticker):\n",
    "        \"\"\"Проверяет формат тикера FUT.XXX\"\"\"\n",
    "        return re.match(r'^FUT\\.\\w{2,5}$', ticker) is not None\n",
    "\n",
    "    def validate_quantity(self, quantity):\n",
    "        \"\"\"Проверяет количество контрактов\"\"\"\n",
    "        try:\n",
    "            qty = int(quantity)\n",
    "            return 0 < qty <= self.max_quantity\n",
    "        except ValueError:\n",
    "            return False\n",
    "\n",
    "    def handle_order(self, action, ticker, price, quantity):\n",
    "        \"\"\"Отправка ордера с валидацией\"\"\"\n",
    "        if not self.validate_ticker(ticker):\n",
    "            return False, \"Invalid ticker format\"\n",
    "            \n",
    "        if not self.validate_quantity(quantity):\n",
    "            return False, f\"Quantity must be 1-{self.max_quantity}\"\n",
    "            \n",
    "        if action.lower() not in self.allowed_actions:\n",
    "            return False, f\"Action must be {', '.join(self.allowed_actions)}\"\n",
    "\n",
    "        try:\n",
    "            adjusted_price = self.apply_slippage(price, action)\n",
    "            logger.info(f\"Adjusted price: {price} -> {adjusted_price}\")\n",
    "            \n",
    "            ticker_code = ticker.split('.')[1]\n",
    "            headers = {\n",
    "                \"X-Api-Key\": CONFIG['finam']['token'],\n",
    "                \"Content-Type\": \"application/json\"\n",
    "            }\n",
    "            \n",
    "            payload = {\n",
    "                \"clientId\": CONFIG['finam']['client_id'],\n",
    "                \"securityBoard\": \"FUT\",\n",
    "                \"securityCode\": ticker_code,\n",
    "                \"buySell\": action.capitalize(),\n",
    "                \"quantity\": int(quantity),\n",
    "                \"price\": float(adjusted_price),\n",
    "                \"property\": \"PutInQueue\"\n",
    "            }\n",
    "            \n",
    "            logger.debug(f\"Order payload: {payload}\")\n",
    "            response = requests.post(\n",
    "                CONFIG['finam']['api_url'],\n",
    "                json=payload,\n",
    "                headers=headers,\n",
    "                timeout=10\n",
    "            )\n",
    "            response.raise_for_status()\n",
    "            return True, response.json()\n",
    "            \n",
    "        except requests.exceptions.RequestException as e:\n",
    "            logger.error(f\"API Error: {str(e)}\")\n",
    "            return False, f\"API Error: {str(e)}\"\n",
    "        except Exception as e:\n",
    "            logger.error(f\"Unexpected error: {str(e)}\", exc_info=True)\n",
    "            return False, f\"Internal error: {str(e)}\"\n",
    "\n",
    "def extract_json(raw_data):\n",
    "    \"\"\"Извлекает JSON из разных форматов\"\"\"\n",
    "    if isinstance(raw_data, dict):\n",
    "        return raw_data\n",
    "        \n",
    "    try:\n",
    "        return json.loads(raw_data)\n",
    "    except json.JSONDecodeError:\n",
    "        pass\n",
    "        \n",
    "    try:\n",
    "        match = re.search(r'\\{[\\s\\S]*\\}', raw_data)\n",
    "        if match:\n",
    "            return json.loads(match.group())\n",
    "    except Exception:\n",
    "        pass\n",
    "        \n",
    "    return None\n",
    "\n",
    "def handler(event, context):\n",
    "    order_manager = OrderManager()\n",
    "    \n",
    "    try:\n",
    "        logger.info(f\"Incoming event: {event.get('body', '')[:200]}...\")\n",
    "        \n",
    "        # Валидация IP (если требуется)\n",
    "        # if event.get('source_ip') not in ALLOWED_IPS...\n",
    "        \n",
    "        data = extract_json(event.get('body', ''))\n",
    "        if not data:\n",
    "            logger.error(\"Invalid JSON format\")\n",
    "            return {\"statusCode\": 400, \"body\": \"Invalid data format\"}\n",
    "            \n",
    "        logger.debug(f\"Parsed data: {json.dumps(data, indent=2)}\")\n",
    "        \n",
    "        # Проверка парольной фразы\n",
    "        if data.get('passphrase') != CONFIG['tradingview']['passphrase']:\n",
    "            logger.warning(\"Invalid passphrase attempt\")\n",
    "            return {\"statusCode\": 403, \"body\": \"Forbidden\"}\n",
    "            \n",
    "        # Извлечение параметров\n",
    "        strategy = data.get('strategy', {})\n",
    "        required = {\n",
    "            'ticker': data.get('ticker'),\n",
    "            'action': strategy.get('order_action'),\n",
    "            'price': strategy.get('order_price'),\n",
    "            'quantity': strategy.get('order_contracts') or strategy.get('order_countracts')\n",
    "        }\n",
    "        \n",
    "        if None in required.values():\n",
    "            missing = [k for k, v in required.items() if v is None]\n",
    "            return {\n",
    "                \"statusCode\": 400,\n",
    "                \"body\": json.dumps({\"error\": \"Missing fields\", \"missing\": missing})\n",
    "            }\n",
    "            \n",
    "        # Исполнение ордера\n",
    "        success, result = order_manager.handle_order(\n",
    "            required['action'],\n",
    "            required['ticker'],\n",
    "            required['price'],\n",
    "            required['quantity']\n",
    "        )\n",
    "        \n",
    "        return {\n",
    "            \"statusCode\": 200 if success else 500,\n",
    "            \"body\": json.dumps({\n",
    "                \"status\": \"success\" if success else \"error\",\n",
    "                \"message\": result if isinstance(result, str) else \"Order executed\",\n",
    "                \"details\": result if not isinstance(result, str) else None\n",
    "            })\n",
    "        }\n",
    "        \n",
    "    except Exception as e:\n",
    "        logger.critical(f\"Handler error: {str(e)}\", exc_info=True)\n",
    "        return {\n",
    "            \"statusCode\": 500,\n",
    "            \"body\": json.dumps({\"error\": \"Internal server error\"})\n",
    "        }"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
